--SELECT * FROM sales_data_sample
--iden s left join 

CREATE VIEW sales_data_samplePOWERBI AS

SELECT a.*, b.DEALSIZE FROM

	(SELECT ORDERNUMBER, QUANTITYORDERED, COUNTRY FROM sales_data_sample) a

	LEFT JOIN
	(SELECT ORDERNUMBER, QUANTITYORDERED, DEALSIZE FROM sales_data_sample) b
	
	  ON a.ORDERNUMBER=b.ORDERNUMBER AND a.QUANTITYORDERED=b.QUANTITYORDERED